apiVersion: skaffold/v2beta12
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
build:
  local:
    push: false
  artifacts:
    - image: skillmarket-front
      context: .
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
          - src: "src/**/*.vue"
            dest: .
          - src: "public/*"
            dest: .
          - src: "*.js"
            dest: .
          - src: ".eslintignore"
            dest: .