apiVersion: v1
kind: Service
metadata:
  name: skillmarket-front-node-port
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31516
  selector:
    app: skillmarket-front